### ISSUE TITLE
Suggestion: npm package

### ISSUE THREAD

**Issue by IOIIOOIO** [nuxodin/ie11CustomProperties#1]
It would be great if this could simply be installed as an npm package for JavaScript dummies like me. It took me a while to figure out how to include it in my Vue project.

Also just want to say thanks, it's a lifesaver for my context. I need the CSS variables to be transpiled dynamically because we are using a CMS backend, so it will need to handle dynamic content. Once we've deployed the project it won't run through WebPack - so something like PostCSS won't work for us.

**Comment by nuxodin** [comment]
Hi, IOIIOOIO
Do you know how to create that npm package?

I'm very glad I could help you with my script!
I still have a request to you: Could you give the project a star? :)

**Comment by IOIIOOIO** [comment]
Will do. I have no clue about the npm package.

**Comment by nuxodin** [comment]
Hi IOIIOOIO
I published a npm pachege.
If you have time, please tell me if it works.
https://www.npmjs.com/package/ie11-custom-properties

**Comment by nuxodin** [comment]
If you find it useful, I'd love a vote on Stackoverflow!
https://stackoverflow.com/a/57000437/4865307

**Comment by IOIIOOIO** [comment]
Done
