### ISSUE TITLE
Support for CSS Keyframe Animations?

### ISSUE THREAD

**Issue by li-zhixin** [nuxodin/ie11CustomProperties#12]
We are attempting to use this for a CSS keyframe animation, but it does not seem like the generated keyframe is being applied properly.

**Comment by nuxodin** [comment]
It's probably too much for a polyfill, I'd have to rerender every animation step.
Do you have a code sample for me?

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
