### ISSUE TITLE
Application load fails after importing the script

### ISSUE THREAD

**Issue by directcuteo** [nuxodin/ie11CustomProperties#13]
I have integrated this polyfill in my Angular 8 application. What I did was to install it through npm and then I have imported it in polyfills.ts using `import 'ie11-custom-properties/ie11CustomProperties'`

the css I want IE to read is: 
`
:root {
      --primary-color: #3ca938;
      -ie-primary-color: #3ca938;
    }`
   ` .primary-color {
      background-color: var(--primary-color) !important;
    }
`

Now when the app is loading in IE (v11) I get an error and nothing is showing up:
`
SCRIPT5113: Use before declaration`
`polyfills.js (3519,3)` -> this is leading to ie11CustomProperties.js line 262

Did I skip any step? How can I make this work? Thank you!

**Comment by nuxodin** [comment]
The script is not written in TS and its not a JS module.
Maybe the problem is that you like to import it in TS?

**Comment by nuxodin** [comment]
I found an other one importing this script.
Maybe it helps:
https://github.com/it-vegard/a11y-reference-website/blob/9f0f965c5a18bc398fe4d466c00182d3577cb5a2/src/components/app/app.js

**Comment by directcuteo** [comment]
Unfortunately it didn't help. That is a React application.

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
