### ISSUE TITLE
Not modifying relative paths causes 404 errors

### ISSUE THREAD

**Issue by RaulJimenezGarcia** [nuxodin/ie11CustomProperties#14]
Hi,

My CSS file has relative paths to load fonts and images.

Not modifying relative paths causes that they're resolved relative to the document instead of the CSS file location.

Any help appreciated.

**Comment by nuxodin** [comment]
Hi Paul

Ich made a new release that should transform your relative urls to absolute urls.
Can you please see if it works for you?

PS:
If you find it useful, I'd love a vote on Stackoverflow!
https://stackoverflow.com/a/57000437/4865307

**Comment by RaulJimenezGarcia** [comment]
Hi,

I've just written [a comment in your code referencing a possible bug](https://github.com/nuxodin/ie11CustomProperties/commit/9077a005db337720c1060d2466e897f726b349a7#r36141714).

PS:
I really appreciate your quick answer.

**Comment by nuxodin** [comment]
fixed

**Comment by nuxodin** [comment]
does it work now?

**Comment by RaulJimenezGarcia** [comment]
It works locally.

Since we have to locate the CSS file in a CDN, now we've got a CORS problem due to the requests made by the fetchCSS function.

We're trying to fix it.

I'll let you know about our progress.

**Comment by nuxodin** [comment]
👍

**Comment by RaulJimenezGarcia** [comment]
I'm afraid it's not up to us fixing the CORS problem and unfortunately we'll have to find some other solution.

Anyway, I really appreciate your help.

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
