### ISSUE TITLE
Doesn't work with SVGStyleElement

### ISSUE THREAD

**Issue by Oikio** [nuxodin/ie11CustomProperties#15]
Throws an error `SCRIPT5007: Unable to get property 'replace' of undefined or null reference` in case of <style> element inside <svg>.

My naive work around was to add:
```js
  function rewriteCss(css) {
    if (!css) return; // this
```

But I guess it shouldn't be marked for check beforehand instead.

![image](https://user-images.githubusercontent.com/1791802/69639832-8e158780-105d-11ea-9f49-1a7cb6b2fcfd.png)

**Comment by nuxodin** [comment]
Thank you for your report.
I made a new version that should solve your SVG problems.

PS:
If you find it useful, I'd love a vote on Stackoverflow!
https://stackoverflow.com/a/57000437/4865307

**Comment by Oikio** [comment]
Thank you for a quick response, it has solved my issue. Nice library by the way.
I will close this issue.

**Comment by nuxodin** [comment]
Thanks 👍

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
