### ISSUE TITLE
Polyfilling not working in IE11.0.9600.19540

### ISSUE THREAD

**Issue by lud-hu** [nuxodin/ie11CustomProperties#16]
Hi,

I've tried to import this library into a react project, but I could not get it to work.
The script is starting (I added a console log at the beginning of the file to check it) but the stylings are not visible in Internet Explorer.

I've tried to import it in different ways:
1. Import the js file in the header.
2. Import it at the end of the body
2. Import it in react's main component. (import("ie11-custom-properties").then()...)

Any ideas on how to debug this?

**Comment by nuxodin** [comment]
Hi

A example page would be great.

Does the Demo Page work in your IE11? 
https://rawcdn.githack.com/nuxodin/ie11CustomProperties/d8abc414fa8ac49135e0029452e253d418d2f866/test.html

If you open the dev-tools and inspect with the DOM-Explorer, you should find css Properties like this:
-ie-theme-color: orange;

**Comment by lud-hu** [comment]
Hi,

thanks for the quick reply!

After handling weird caching problems in IE11 I finally found a solution that worked in combination with the React framework:

index.tsx
`import "ie11-custom-properties";`

Then the js lib is properly bundled into the build and loaded on startup of the app.
So if anyone else wants to use this with React, this is probably the easist and most convenient way to go (to also get updates of the lib via npm).

Sorry for the (too early stated) issue and thanks for this great lib!

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
