### ISSUE TITLE
Trying to parse just the style tags IE 11 throws a SCRIPT5113 runtime error

### ISSUE THREAD

**Issue by RaulJimenezGarcia** [nuxodin/ie11CustomProperties#18]
Hi,

I'm trying to parse just the style tags - neither the link tags nor the elements with ie-style attribute. To achieve this I've erased two blocks of code from your polyfill and IE 11 throws a SCRIPT5113 runtime error.

The blocks are:

https://github.com/nuxodin/ie11CustomProperties/blob/815b20aba4a5c629211227661a2c18a751468358/ie11CustomProperties.js#L131

https://github.com/nuxodin/ie11CustomProperties/blob/815b20aba4a5c629211227661a2c18a751468358/ie11CustomProperties.js#L149

Any help will be appreciated.

**Comment by nuxodin** [comment]
Hi,

I don't get it.
Do you have an example page?

**Comment by nuxodin** [comment]
If you erase just the two blocks, i see no problems...

**Comment by RaulJimenezGarcia** [comment]
It seems that the source of my problem is [koala-app](http://koala-app.com/), the software I'm using to combine and minify my js files.

I've fixed it just by loading your polyfill from a distinct file from my main js file.

I really appreciate your help.

**Comment by nuxodin** [comment]
👌👍

**Comment by nuxodin** [comment]
PS:
If you like the polyfill, you can support my by:
Add a ⭐️
Vote for this solution at stackoverflow https://stackoverflow.com/a/57000437/4865307
And tweet about it.
