### ISSUE TITLE
I'm getting Syntax Error when used with Nuxtjs

### ISSUE THREAD

**Issue by prajngen** [nuxodin/ie11CustomProperties#19]
[Line 33,9] :  var els = root.querySelectorAll(listener.selector), i = 0, el;

is being flagged by Internet Explorer as Syntax Error...don't know why

**Comment by nuxodin** [comment]
Seams the querySelectgorAll argument (listener.selector) is not valid.
Can you print out "listener.selector" just before that line?
`console.log(listener.selector)`

**Comment by nuxodin** [comment]
Hi
Did you found the problem?

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
