### ISSUE TITLE
SCRIPT5113: Use before declaration

### ISSUE THREAD

**Issue by hogash** [nuxodin/ie11CustomProperties#20]
Hey Tobias,

I'm getting these errors in IE11's console:
```
SCRIPT5113: Use before declaration
eval code (58) (296,3)
```
The error marks the colon with red https://d.pr/i/UVIBt7 . Maybe has anything to do with the colon symbol?

The line in particular being: https://github.com/nuxodin/ie11CustomProperties/blob/master/ie11CustomProperties.js#L290

If i `console.log(selector)` it prints `:root`. If in the `selectorAddPseudoListeners()` function i add `return;` at the begining to prevent executing the theme, it'll keep on adding these kinds of errors, for example on line  https://github.com/nuxodin/ie11CustomProperties/blob/master/ie11CustomProperties.js#L368 .

Happen to have any idea about this one?

**Comment by nuxodin** [comment]
Maybe the problem is that you try to import it in TS?

**Comment by hogash** [comment]
I'm using something like:

```
if (!(window.CSS && window.CSS.supports && window.CSS.supports("(--foo: red)"))) {
  $.getScript('path/to/file');
}
```

Also tried loading as you recommended:
```
<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="yourJsPath/ie11CustomProperties.js"><\x2fscript>');</script>
```

But i realise i haven't loaded normally without IE11 detection checks.

**Comment by nuxodin** [comment]
This does not work?
`<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="yourJsPath/ie11CustomProperties.js"><\x2fscript>');</script>`

**Comment by hogash** [comment]
Sorry, i was so sure i tried everything. Em using WordPress, and i eventually loaded like you recommend, but just tried hooking into `wp_head` with 0 priority and seems to run. My only issue now is that it's loading the page really slow. I'll try to debug myself.

**Comment by nuxodin** [comment]
The polyfill is mutch faster now.

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307

**Comment by IamCloud** [comment]
Getting the same error and I am using this method:
`<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="yourJsPath/ie11CustomProperties.js"><\x2fscript>');</script>`

**Comment by solemone** [comment]
@IamCloud  I had the same issue if a `<style>` tag came before  loading the polyfill.

__is not working:__
```
<style>your styles in the HTML document</style>
<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="yourJsPath/ie11CustomProperties.js"><\x2fscript>');</script>
```

__is working:__
```
<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="yourJsPath/ie11CustomProperties.js"><\x2fscript>');</script>
<style>your styles in the HTML document</style>
```

I had no problems with external css files. With external css files loaded via `<link rel="stylesheet" href="/css/styles.css">` the order does not matter—everything worked.

Maybe there is an issue with inline `<style>` tags . @nuxodin do you have an idea what it could be?

**Comment by eddyw** [comment]
@solemone 🤦‍♂️ thanks, it was driving me crazy. I'm curious though why the order matters with inline `<style>` tags.
