### ISSUE TITLE
Performance with angular

### ISSUE THREAD

**Issue by hghammoud** [nuxodin/ie11CustomProperties#21]
I added this in the polyfills.ts the rendering is working great however the performance is a stale mate. Its rendering more than 4k stylesheet.

It keeps on adding empty style sheets until IE stops responding.

This is an example of my input.scss.
```
:host {
  display: flex;
  flex: 1;
  --font-size: var(--fs-18);
  --font-weight: var(--light);
  --input-color: var(--color-app-input);
  --placeholder-color: var(--color-app-placeholder);
  --bg-color: var(--color-app-dark-gray);
  --width: 100%;
  --height: 4.6rem;
  --border-radius: 0.4rem;
  --border: none;
  --error-color: var(--color-app-warning-bordered);
}

  .container {
    display: flex;
    flex-direction: column;
    flex: 1;
    justify-content: space-between;
  }

  .section {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .errors {
    color: var(--error-color);
  }

  .input {
    display: flex;
    flex: 1;
    box-sizing: border-box;
    border-radius: var(--border-radius);
    width: var(--width);
    min-height: var(--height);
    max-height: var(--height);
    border: var(--border);
    background-color: var(--bg-color);
    padding: 0 1.2rem;
    color: var(--input-color);
    font-size: var(--fs-12);

    &::placeholder {
      color: var(--placeholder-color);
    }
  }


  .label {
    font-weight: var(--semibold);
    color: var(--color-app-p);
    letter-spacing: 0.05rem;
    margin-bottom: 0.5rem;
  }

  // used to override display: inline-block from ng2TelInput library
  ::ng-deep {
    .iti {
      display: flex;
    }
  }

  .input-wrapper {
    position: relative;
    display: flex;


  }

  .input.error {
    border: 0.1rem solid var(--error-color);
  }

  .input:focus {
    border: 0.1rem solid var(--color-app-cyan);
    box-shadow: 0 0 5px rgba(85, 183, 227, 0.5);
    background-color: #f7f7f7 !important;
  }

  .circle {
    height: calc(var(--height) / 2);
    width: calc(var(--height) / 2);
    border-radius: 50%;
    background-color: var(--error-color);
    position: absolute;
    flex: 1;
    align-self: center;
    right: 1rem;
    display: flex;
    align-items: center;
    justify-content: center;

    fa {
      padding-top: 0.2rem;
    }
  }
```

**Comment by nuxodin** [comment]
Hi, 
Performance depents mostly on how many elements are affected by custom-properties.
Each element gets its own style-sheet.
Once I find the time and have a clear mind, I will improve performance by handling root custom properties differently.

**Comment by hghammoud** [comment]
I think these is a bug somewhere. There is an infinite loop that is creating empty <style> tags.

**Comment by nuxodin** [comment]
can you test with the actual master-branch?

**Comment by nuxodin** [comment]
any news on this?

**Comment by hghammoud** [comment]
I ll will be checking it today or tomorrow morning and get back to you.

**Comment by nuxodin** [comment]
I made a new release 2.7.2
You can expect great increases in performance.

**Comment by hghammoud** [comment]
After various tests. it ended up removing this css selector and replaced it with something less generic. 
It was related to the not(tspan) the * solo works well.
I ll pull the new version. Thanks for you time and investment.

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
