### ISSUE TITLE
Not working in Internet Explorer

### ISSUE THREAD

**Issue by quang-sunlight** [nuxodin/ie11CustomProperties#22]
![Untitled](https://user-images.githubusercontent.com/58925812/70982735-1978ba80-20ea-11ea-822b-69127640471a.png)

**Comment by quang-sunlight** [comment]
I am using angular 8. so I could not translate <style> to @import. I think that's why it doesn't work

**Comment by nuxodin** [comment]
I don't have enough information to reproduce the problem.

**Comment by nuxodin** [comment]
I close the issue for now.
Will be great if you can provide me a minimal example.

**Comment by owennewo** [comment]
I realize this issue is closed but for those who want an example of using this polyfill with angular 8 checkout:

- Editor:  https://stackblitz.com/edit/angular8-ie11-custom-properties
- IE11 demo link: https://angular8-ie11-custom-properties.stackblitz.io

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
