### ISSUE TITLE
Access-Control-Allow-Origin error

### ISSUE THREAD

**Issue by Mangatt** [nuxodin/ie11CustomProperties#26]
Hello,
we have web files located on multiple separated domains like this:

- example.com - location of HTML page
- files.example.com - location of CSS
- cdn.differentexample.com - location of this polyfill and someother CSS

Unfortunately, IE11 throws Access-Control-Allow-Origin error and XMLHttpRequest error 8070013. Is there a way how to make this setup work?

**Comment by nuxodin** [comment]
Hi 
To polyfill Custom Properties, i have to load the contents of the css-file.
This is not possible crossdomain without cors-headers.

The css-files on the oder domains should be delivered with headers like:
Access-Control-Allow-Origin: http://example.com 
Or 
Access-Control-Allow-Origin: *

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307

**Comment by patricknelson** [comment]
For what it's worth, if you still want to allow access to the CSS files without being _too_ permissive (and if you're running Apache) you could  potentially add an entry like this in your `.htaccess`:

```apache
# Allow access across domains to CSS files.
<FilesMatch "\.css">
	Header set Access-Control-Allow-Origin "*"
</FilesMatch>
```

Feel free to replace `*` with any domain you wish (or leave it alone to keep it completely permissive, which is fine in my use case).
