### ISSUE TITLE
Unsupported selectors by querySelectorAll

### ISSUE THREAD

**Issue by michaljerabek** [nuxodin/ie11CustomProperties#28]
If a selector is not supported by `querySelectorAll` it throws an error and then many of CP don't work. If the code inside `c1.onElement` function is wrapped in a `try/catch`, everything seems to work better.

**Comment by nuxodin** [comment]
Thank you for your feedback!
Do you have a example of a selector that throws?

**Comment by michaljerabek** [comment]
It's actually more complicated than I thought.

Selector `a:not(:hover):not(:focus)` is send to `querySelectorAll` as `a:not()`. Some other selector ends up as an empty string (hard to say which one).

**Comment by nuxodin** [comment]
It is difficult to parse this selector just with a regex.
I leave this issue open, maybe I find a solution sometime.

**Comment by michaljerabek** [comment]
Ok. Could you consider to add that `try/catch`?

**Comment by nuxodin** [comment]
Ok, i made a new release.
