### ISSUE TITLE
Doesn't work correctly inside calc

### ISSUE THREAD

**Issue by bogdanbeniaminb** [nuxodin/ie11CustomProperties#29]
When using a CSS variable inside calc, it replaces it incorrectly and this throws an error in IE (unspecified error), because it tries to apply a wrong value.

If we have
`top: calc(var(--menu-space, 0) + 10px);`

then it tries to apply the following:
`style['top'] = "calc(0) + 10px";`

It breaks the paranthesis and thus applies an incorrect value.

**Comment by nuxodin** [comment]
Hi bogdanbeniaminb

Thank you for your feedback.
I found the issue, it works now, with my new update!

**Comment by bogdanbeniaminb** [comment]
Thanks a lot, @nuxodin .

Any chance you could also increase the version number, so that it gets updated to NPM as well?

Thank you!

**Comment by nuxodin** [comment]
Yes, for sure, its there now.

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307

**Comment by bogdanbeniaminb** [comment]
Voted!
