### ISSUE TITLE
Minified version release

### ISSUE THREAD

**Issue by abejenaru** [nuxodin/ie11CustomProperties#31]
Hi, just wondering if it would be possible to release a minified/compressed version as part of the package.

**Comment by nuxodin** [comment]
Hi, thank you for your Feedback.

I have no buildsystem to automate this and I don't want to do this by hand with every release.
I think if you use this polyfill with NPM you can minify it with your own build system or just compress it here:
https://skalman.github.io/UglifyJS-online/
What do you think?

**Comment by abejenaru** [comment]
Thanks, no problem for minifying as part of my dependency update process - it might be something to consider yourself if you set up an automatic build system. Thanks for your work!

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
