### ISSUE TITLE
Can't get CSS variables to work together with calc()

### ISSUE THREAD

**Issue by 3SCadmin** [nuxodin/ie11CustomProperties#38]
Hi,

IE already supports **calc( )**
But I can't get it to work in combination with CSS variables using your polyfill.

Sample Code:
`<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="ie11CustomProperties.js"><\x2fscript>');</script>`
`<style>`
`  :root {`
 `     --base_width:3px;`
`      --bg_color:green;`
`  }`
`.A1 {`
`    padding:1em;`
`    width:50px;`
`    border-left:calc(1px*5) solid red;`
`    border-right:calc(var(--base_width)*5) solid red;`
`    background-color:var(--bg_color);`
`  }`
`</style>`
`<body> `
`<div class='A1'>test</div>`
`</body>`

in IE 11 I get this output:
![image](https://user-images.githubusercontent.com/45569168/76886040-18396400-6878-11ea-8aa2-7ef474f2e512.png)

So 

1. Calc works (border-left is rendered 5px wide
2. CSS variables work (background is rendered green
3. But calc + CSS variables does not work (border-right is not rendered at 15px)

Chrome renders the above code correctly:
![image](https://user-images.githubusercontent.com/45569168/76887364-1375af80-687a-11ea-910f-398f1f32ba06.png)

**Comment by skielbasa** [comment]
I'm experiencing this too. From what I can tell, it seems like this polyfill just doesn't look inside `calc()` to check for custom properties at all. 

If you look on an elm that the polyfill corrected, it'll have an `iecp-needed="true"` attribute on it. I had some elements who's only custom properties lived inside a `calc()`, and those elements wouldn't have the `iecp` attribute added.

For my use case, I was able to refactor to not need `calc()` as I was just using it to invert a value.

**Comment by nuxodin** [comment]
Hi
"calc" is a beast and I believed to implement it correctly.
See the "nested calc " in the test-cases:
https://rawcdn.githack.com/nuxodin/ie11CustomProperties/6c465d21a8c043a45cba939995bb434966048377/tests.html

What Version do you use?

**Comment by skielbasa** [comment]
I'm using v3.0.6. (pulled it straight from the file list on the repo's front page).

I wonder if my issue comes from the fact that this site is built with lots of tiny .css files (one for each component for their specific styles) that reference custom properties from a 'main' .css file that has the global styles in.

Either way this polyfill has made life a LOT simpler, so thank you for your time and effort.

**Comment by nuxodin** [comment]
@skielbasa 
Thank you, if you like to provide a small text-case, i will check it.

@3SCadmin 
Your exact example seams to work in my case:
![grafik](https://user-images.githubusercontent.com/16326/78074330-d691d880-73a2-11ea-9894-f333041dd78b.png)

**Comment by nuxodin** [comment]
As i tested it and it worked, i close the issue
