### ISSUE TITLE
Processing order of link and style elements

### ISSUE THREAD

**Issue by carnilino** [nuxodin/ie11CustomProperties#39]
I have the theme css in <link> element in <head> and overriding styles in <style> element first thing after opening <body> tag. The <style> get processed for IE11 before the <link>, which makes the <link> override <style>. (I found the processing order via logging [inside `onElement` function](https://github.com/nuxodin/ie11CustomProperties/blob/5b90fe2e75539971f9c1b85856fad9598a8cf984/ie11CustomProperties.js#L131). I'm using 3.0.5 release verson.

Simplified code:
```
<head>
   ...
   <script src='http://localhost/.../js/ie11CustomProperties.min.js'></script>
   <link rel='stylesheet' href='http://localhost/.../css/theme.css' media='all' />
   ... // all other scripts and styles are after these two
</head>
<body>
   <style> **overriding css**</style>
</body>
```

Via testing i found that reordering the scripts and styles didn't help in any combination, even with jquery. It might have to do with caching - when the ie11 script runs.

This is log for **incorrect** processing order, highlighted are the ie11 script and theme css:
![incorrect](https://user-images.githubusercontent.com/33524034/77212912-3bc70d80-6b09-11ea-91ae-faa32d8fb650.PNG)

This is log for **correct** processing order:
![correct](https://user-images.githubusercontent.com/33524034/77212978-82b50300-6b09-11ea-8ad4-30bc42070c79.PNG)

Testing showed that the order is incorrect whenever the _time_ value in network debugger for ie11 script is 0. Time of theme css doesn't play a role.

**Comment by nuxodin** [comment]
Hi
Which css-code exactly overwrites which css-code?

I mentoned in the readme:

> Specificity for properties containing "var()" is little highter if vars are not served by root, cause each selector gets an additional class-selector eg. #header results in #header.iecp_u44

So if you have the css:
```css
a {
   color:var(--green);
}
```
It will overwrite:
```css
a {
   color:red;
}
```
Even if this comes after.

Can this be your issue?

**Comment by carnilino** [comment]
```
:root {
   --color-primary: red;    // from <style>
}
```
is being overwritten by
```
:root {
   --color-primary: green;    // default color in <link src="theme.css">
}
```

**Comment by nuxodin** [comment]
Hm, I know where the mistake might be, but right now I don't have time.
I'll leave the issue open.

**Comment by gsfitis** [comment]
Same issue here. Can we help so this can be fixed?

**Comment by nuxodin** [comment]
@jonathantneal made PR with a big improvement, the order of the links should now remain untouched.
Can you retest?
New version 4.1.0

**Comment by gsfitis** [comment]
I can confirm that here is fixed. Thanks. I didn't do tests like @carnilino, but had several pages where I could tell the order was messed up from the page look and feel and the inspected code. All these gone after I move to 4.1.0. Thanks again.

**Comment by nuxodin** [comment]
@gsfitis thanks.

I think I can close it.
You're welcome to reopen it if the problem persists.
