### ISSUE TITLE
Usando @import

### ISSUE THREAD

**Issue by StevenAza** [nuxodin/ie11CustomProperties#42]
Cuando intento correr el script, los atributos quedan vacíos. El archivo css tiene un import donde están las variables.

Adjunto evidencia:

![image](https://user-images.githubusercontent.com/13968409/79912105-20407280-83e7-11ea-980a-11a5731373a6.png)

![image](https://user-images.githubusercontent.com/13968409/79912128-29c9da80-83e7-11ea-93bd-9e872d213d48.png)

![image](https://user-images.githubusercontent.com/13968409/79912157-33534280-83e7-11ea-9c34-ca3c8703822f.png)

**Comment by nuxodin** [comment]
@imports are not supported.
Would it be possible for you not to use imports?
Since import is not recommended anyway, I will probably not implement it.
