### ISSUE TITLE
Dynamic add class which has customer properties.

### ISSUE THREAD

**Issue by ruojianll** [nuxodin/ie11CustomProperties#45]
I have a gallery component. Class 'active' witch has customer property is used to active current item. The default item (1st item) has the default 'active' class, this lib works fine but when I add 'active' class to other items, the lib didn't compile ie compatible class for it.

Is there any way to make elements has the same ie name for classes or define a pre compile class witch element not include when page loaded?

**Comment by nuxodin** [comment]
i made 4.0.0, can you retry?
