### ISSUE TITLE
Error:  Unable to get property 'color' of undefined or null reference

### ISSUE THREAD

**Issue by brunnerh** [nuxodin/ie11CustomProperties#46]
Is there something to watch out for when using this polyfill?
All of my HTML and styles are generated client-side using *Svelte*.

```
TypeError: Unable to get property 'color' of undefined or null reference
   at parseRewrittenStyle (eval code:247:9)
   at activateStyleElement (eval code:280:7)
   at foundStyle (eval code:157:5)
   at onElement (eval code:34:7)
   at Anonymous function (eval code:160:3)
   at eval code (eval code:2:2)
   at ./node_modules/ie11-custom-properties/ie11CustomProperties.js (http://localhost:8080/bundle.js:8815:1)
```

**Comment by nuxodin** [comment]
Latest version?
Do you have a example online?

**Comment by brunnerh** [comment]
It should have been the latest version. I installed the package not long before reporting the issue.
Currently there is no online example. I will try to isolate the problem.

**Comment by brunnerh** [comment]
It looks like some state is declared too late. If i move the following variables to the top, the errors are resolved:

```js
// beta
const styles_of_getter_properties = {};
	
// draw queue
let drawQueue = new Set();
let collecting = false;
let drawing = false;
```

However, the variables are currently not being resolved correctly...

**Comment by brunnerh** [comment]
After patching the script as noted, i tried to create a minimal working theme switch and was unable to do so. Neither the patched version, nor the original worked. The example can be found here: https://brunnerh.github.io/ie-11-prop-issue-example/

**Comment by brunnerh** [comment]
I noticed that once i called `style.setProperty` on the document element, all the properties got updated correctly. I added a button to the demo to illustrate this. So it seems that there currently is a lack of change detection to make this work automatically.

**Comment by nuxodin** [comment]
Can you check with the current version 4.0

**Comment by nuxodin** [comment]
Thank you for your feedback.
The new version 4.0.1 should work now.

**Comment by nuxodin** [comment]
I think it should work now, so i close the issue.
