### ISSUE TITLE
Not working after minify

### ISSUE THREAD

**Issue by sbatezat** [nuxodin/ie11CustomProperties#48]
Angular is using Terser to minify JS files. One option set by the CLI is "pure-getter: true".
This option is removing the following line from this library:

style['z-index']; // ie11 can access unknown properties in stylesheets only if accessed a dashed known property

Could you please update it to ensure it's never removed by such process?
For example, you could do something like this:

```
if (style['z-index'] === undefined) {
   return;
}
```

**Comment by sbatezat** [comment]
I've just done a pull request with that proposal
https://github.com/nuxodin/ie11CustomProperties/pull/49

**Comment by nuxodin** [comment]
Good catch, thank you!
