### ISSUE TITLE
Does not support negation pseudo-class

### ISSUE THREAD

**Issue by jianliao** [nuxodin/ie11CustomProperties#5]
CSS selector: `:not(:active).spectrum-Textfield.focus-ring`

The following function will lead to an error.
```javascript	
function addGettersSelector(selector, properties) {
    selectorAddPseudoListeners(selector);
    var selectorWithoutPseudo = selector.replace(regPseudos,'');
    c1.onElement(selectorWithoutPseudo, function (el) {
	addGetterElement(el, properties, selector);
	drawElement(el);
    });
}
```

Because selectorWithoutPseudo will be `:not().spectrum-Textfield.focus-ring` which is a invalid css selector.

**Comment by nuxodin** [comment]
Hi jianliao
Thank you for your feedback!
I changed the code, so your selector should work.

Can you test please?

------------
Tweet about if you like it.
Vote this solution at stackoverflow https://stackoverflow.com/a/57000437/4865307

**Comment by jianliao** [comment]
Thanks for the quick response. The change fixed the issue. But new one comes.
The style trys to get active looks like: `.spectrum-Link-ie-quiet:hover, .spectrum-Link--subtle:hover`. But selector is like: `.spectrum-Link-ie-quiet,`.  Here is the call stack. Thanks!
![image](https://user-images.githubusercontent.com/1207520/62149060-c4a9e400-b2af-11e9-81a7-5851cbe877b5.png)

**Comment by nuxodin** [comment]
Thank you again for reporting this.
I fixed your usecase.

To make vars work in IE, i have to replace `--foo` to `-ie-foo`
I had to improve my regular expression so I wouldn't replace "--" it in the selector.

Does it work now?

**Comment by jianliao** [comment]
Found another issue. https://github.com/nuxodin/ie11CustomProperties/blob/fed5b47236c3dc5d2978ca0b92325b3275c2514d/ie11CustomProperties.js#L254

Can not assume el always has classList property, for instance SVG path.

**Comment by nuxodin** [comment]
You can use this polyfill:
```js
function copyProperty(prop, from, to){
    var desc = Object.getOwnPropertyDescriptor(from, prop);
    Object.defineProperty(to, prop, desc);
}
if ('classList' in HTMLElement.prototype && !('classList' in Element.prototype)) {
    copyProperty('classList', HTMLElement.prototype, Element.prototype);
}
```
I'm not sure yet if I integrate this into the custom properties polyfill

**Comment by nuxodin** [comment]
Are you happy now?

**Comment by jianliao** [comment]
Sorry, I didn't have a chance to try it yet.

**Comment by nuxodin** [comment]
As the real Issue is solved, i close it.

**Comment by nuxodin** [comment]
Hi Jianliao
I just added the little classList-polyfill to the code.

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
