### ISSUE TITLE
4.0.0 has script errors in IE11

### ISSUE THREAD

**Issue by teetotum** [nuxodin/ie11CustomProperties#51]
@nuxodin First things first: thank you for this library. I'm amazed this library exists and it seems to be exactly what I need in my current project. I just installed the 4.0.0 version and imported into my index.js and fired it up in IE11 and had a script error. (my project is ES6 and is transpiled down to ES5)

Error: usage before declaration
line 214 in ie11CustomProperties.js
the used variable is `styles_of_getter_properties`
and I think this happens because it is declared in line 197 as a `const` and IE11 does not recognize the keyword `const` and therefore seems to ignore it.
You used `const` throughout the script file. To my knowledge this therefore would not work in IE11
(Maybe this got into the file by accident: might be some tool changed all var to const onSave? *Prettier* or *eslint*?)

**Comment by nuxodin** [comment]
Hi Teetotum
The script does need a transpiler.
Its recommened to load the polyfill like this:
<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="yourJsPath/ie11CustomProperties.js"><\x2fscript>');</script>
If you do so, the scripts only loads by IE11

**Comment by nuxodin** [comment]
Thank you for your feedback.
The new version 4.0.1 should now work fine.

**Comment by nuxodin** [comment]
I think it should work now, so i close the issue.
