### ISSUE TITLE
"const" keyword not supported in for-in loops

### ISSUE THREAD

**Issue by FrDH** [nuxodin/ie11CustomProperties#53]
According to [can i use](https://caniuse.com/#search=const), IE11 does not support the `const` keyword in for-in and for-of loops.
This would mean [this line](https://github.com/nuxodin/ie11CustomProperties/blob/master/ie11CustomProperties.js#L331) is interpreted different from what you'd expect.

Not sure how to test if this actually fails or produces an error, but In general I wouldn't use `const` at all if you're not going to transpile it.

Anyway, thanks for the great script.

**Comment by nuxodin** [comment]
Thanks for dipping into my code.
I think the point is, it doesn't work that way:
`for (const x in ...)`
See http://kangax.github.io/compat-table/es6/#test-const_for-in_loop_iteration_scope

**Comment by FrDH** [comment]
Ok, couldn't get the script not to work so you might be right :)
