### ISSUE TITLE
Polyfill pegs IE11 CPU

### ISSUE THREAD

**Issue by mherchel** [nuxodin/ie11CustomProperties#54]
** Description **  
I'm evaluating this polyfill for potential inclusion in a Drupal core theme at https://www.drupal.org/project/olivero/issues/3150283

What I'm finding is that the polyfill is pegging the CPU at 100% for far too long. 

** Version **  
v4.0.1

** To Reproduce **  
Live working example with polyfill: 
https://polyfill-2-suc1r45wz6rh1vprw9741vkh9ptosyyq.tugboat.qa/

CSS for the site: 
https://git.drupalcode.org/project/olivero/-/tree/polyfill-2/css/src

Video of the issue happening:
https://www.youtube.com/watch?v=qW8BlgWtOuA

**Comment by nuxodin** [comment]
Thank you form your Feedback.

I have a different version of IE11
![grafik](https://user-images.githubusercontent.com/16326/84658773-b0e28d00-af16-11ea-9a92-3046b83e80fe.png)

Yours is probably not the version used by current visitors:
![grafik](https://user-images.githubusercontent.com/16326/84659008-0c147f80-af17-11ea-8ff9-7cab5fcc2536.png)

Maybe it makes a difference

Well, I'll wait for Tubgoat...

**Comment by mherchel** [comment]
Fixed the tugboat preview (and updated the issue description). New URL is https://polyfill-2-suc1r45wz6rh1vprw9741vkh9ptosyyq.tugboat.qa/

**Comment by mherchel** [comment]
I'll update IE later today or tomorrow and see if that makes a difference, too

**Comment by nuxodin** [comment]
Thx.

Here is a Video from my PC
https://youtu.be/JjnvxkiCscQ

This my CPU
![grafik](https://user-images.githubusercontent.com/16326/84686994-3b3de780-af3d-11ea-8455-eca783f04118.png)

Definitely better than in your video but it's been going on for quite a while.
139 KB of CSS is just a bit much.
"charCode tokenization" could possibly help:
https://twitter.com/jon_neal/status/1266375550307692547
But that would be a relatively big change...

**Comment by nuxodin** [comment]
Is it not a mistake that the same CSS is used 3 times here?

![grafik](https://user-images.githubusercontent.com/16326/84688027-e56a3f00-af3e-11ea-8f85-566d69cef164.png)

**Comment by mherchel** [comment]
Yeah, that does look like a mistake. I had to refactor the code down from PostCSS custom properties (which had a log of imports.... I guess I missed some).

**Comment by mherchel** [comment]
I'll remove those duplicate `:root` declarations, and then update IE in my VM, but it might not be till later tonight or tomorrow.

**Comment by mherchel** [comment]
FYI, I removed the duplicate custom property declaration, and it's still pegging the CPU. Tugboat is rebuilding now. 

I downloaded the latest IE update from Microsoft and installed it (and rebooted), but the version number on the about dialog didn't change 🤷‍♂️

**Comment by nuxodin** [comment]
Yeah, https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge
IE11 on Windows 7 is out of support.

**Comment by nuxodin** [comment]
My new Video shows that its better, although not perfect :
https://youtu.be/2FWMXnUJiyk

**Comment by nuxodin** [comment]
@jonathantneal made PR with a improvment, maybe its faster in your case now!?
New version 4.1.0

**Comment by nuxodin** [comment]
Pleas reopen if needed, thx.
