### ISSUE TITLE
Docs: Add CDN option?

### ISSUE THREAD

**Issue by coliff** [nuxodin/ie11CustomProperties#55]
Thanks for this polyfill. It's working great for me :-)  I loaded it from JSDelivr.net CDN which was fast and easy. Maybe this could be added to the docs as an option? As a bonus, JSDelivr offers a [minified version](https://cdn.jsdelivr.net/gh/nuxodin/ie11CustomProperties@4.0.1/ie11CustomProperties.min.js).

```
<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="https://cdn.jsdelivr.net/gh/nuxodin/ie11CustomProperties@4.0.1/ie11CustomProperties.min.js"><\x2fscript>');</script>
```

**Comment by nuxodin** [comment]
Yes, good idea!
Do you like to make a PR to be listed as a contributor?
