### ISSUE TITLE
It doesn't consider `!important` in the variables.

### ISSUE THREAD

**Issue by akshymalvia** [nuxodin/ie11CustomProperties#6]
![Screenshot 2019-08-06 at 18 12 46](https://user-images.githubusercontent.com/30196863/62540764-f30e5d00-b875-11e9-9e6b-b41f6328e15c.png)

**Comment by nuxodin** [comment]
Hi akshymalvia
Thank you for your feedback!

The new release implements !import 
on getters { --foo:bar !important; }
and setters { background-color:var(--foo) !important; } 

----
P.S.:
Dont forget to star this project.
And consider to vote this script as a solution to this question:
https://stackoverflow.com/a/57000437/4865307
Tweet and write about it if you like.
