### ISSUE TITLE
SCRIPT8: The download of the specified resource has failed.

### ISSUE THREAD

**Issue by ned-martin** [nuxodin/ie11CustomProperties#67]
** Description **  
SCRIPT8: The download of the specified resource has failed.
line 121,4
			return fetchCss(el.href, function (css) {

** Version **  
v4.1.0

Unfortunately I can't give you the site which produces this error as it's confidential and under development so I can't give you a way to reproduce this error, however the URL that it can't access is `<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>` and the site is hosted during development on an HTTP (not HTTPS) connection so that's evaluating to http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css

**Comment by nuxodin** [comment]
It is not possible to load / correct css across domains.
