### ISSUE TITLE
Unable to get property 'nodetype' of undefined or null reference

### ISSUE THREAD

**Issue by anthonyfang02** [nuxodin/ie11CustomProperties#68]
** Description **  
In an Angular application when navigating between routes or when an element is appended and removed that is using inline ie-style, an error is thrown. The error is seen below, it seems to be the case where the element is destroyed and no longer on the DOM.

![image](https://user-images.githubusercontent.com/13523782/90468804-418b4400-e0e5-11ea-91b8-e484287817a7.png)

When adding a null check for this element value it fixes the issue.

![image](https://user-images.githubusercontent.com/13523782/90468958-9cbd3680-e0e5-11ea-991d-66545d6f793a.png)

** Version **  
4.1.0

**Comment by tmartin42** [comment]
Had the same issue with an angularJS router. Would love to have the fix implemented
