### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by rkumorek** [nuxodin/ie11CustomProperties#7]
Hey,

I wanted to try out this nice looking polyfill but currently I am encountering an issue on IE. Whenever the script runs I get error on this line https://github.com/nuxodin/ie11CustomProperties/blob/master/ie11CustomProperties.js#L52 saying "Object doesn't support property match".
When I injected local copy of this script and console.logged `target` it pointed to `[Object SVGSVGElement]`. I am not sure if that's because I am using `<svg><use /></svg>` to inject svg icons from sprite. 

I can try creating simple repo showcasing the issue as soon as I get some time.

Any help appreciated.

**Comment by nuxodin** [comment]
Hi Rkumorek

I made SVG work with this polyfill.
Can you test your Code? 
If it does not work with the new version yet, I would be grateful for example code.

**Comment by nuxodin** [comment]
If you find it useful, I'd love a vote on Stackoverflow!
https://stackoverflow.com/a/57000437/4865307
