### ISSUE TITLE
Question: How do you make sure this code only runs in IE11?

### ISSUE THREAD

**Issue by avilde** [nuxodin/ie11CustomProperties#8]
Hi!

I was looking at the example page and your code and could not find the logic which makes this poly-fill only execute in IE11.

How do you make sure this is indead only executed in IE11 and not in Edge, Chrome, Firefox?

**Comment by nuxodin** [comment]
Hi Avilde
The browser-features check is here:
https://github.com/nuxodin/ie11CustomProperties/blob/master/ie11CustomProperties.js#L107
I just improved it.

**Comment by nuxodin** [comment]
If you find it useful, I'd love a vote on Stackoverflow!
https://stackoverflow.com/a/57000437/4865307
