### ISSUE TITLE
Does not work with cssinjs libraries which use insertRule

### ISSUE THREAD

**Issue by dzearing** [nuxodin/ie11CustomProperties#80]
When a style element is injected, and then `sheet.insertRule` is called to insert rules that define and consume variables, the polyfill will not pick up on these variable references and therefore will not reflect the variable values.

This fundamentally breaks this from working. 

In our library `@uifabric/merge-styles`, we have an injectionMode config option to change injection to create text elements for rules and to use `appendChild` in the style element to add rules. This works as a workaround. But I'd imagine this may not be an option for every library.

Is there something about `insertRule` that is not observable?

**Comment by nuxodin** [comment]
Thanks for the feedback.
I think the complexity to cover this requirement is too big for the scope of this project.
