### ISSUE TITLE
Properties with color defined as hsla are not applied

### ISSUE THREAD

**Issue by miluoshi** [nuxodin/ie11CustomProperties#81]
**Description**  
Any css property referencing css custom property defined as hsla css function is not applied, even though [it is supported by IE11](https://caniuse.com/mdn-css_types_color_alpha)

**Version**  
4.1.0

**To Reproduce**  
https://jsbin.com/mukogak/edit?html,css,js,output

**Comment by nuxodin** [comment]
Hi miluoshi
IE11 does not support the alpha-value as percent
use `hsla(0, 0%, 0%, 0.6)` instead of `hsla(0, 0%, 0%, 60%)`

**Comment by miluoshi** [comment]
@nuxodin thank you, I didn't realize that.
