### ISSUE TITLE
Feature Request: Callback when done

### ISSUE THREAD

**Issue by dotherightthing** [nuxodin/ie11CustomProperties#83]
In IE11, use of this polyfill adds a noticeable lag before the page becomes fully interactive (v4.1.0).

I've mitigated this by post-processing my CSS with [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties). This allows the page to render the core styles right away, with inline overrides being applied once the ie11CustomProperties polyfill has finished doing its thing.

But this mitigation only helps with the perceived loading time. The user still has to wait for the ie11CustomProperties polyfill to finish before the page becomes interactive.

Adding a callback would allow me to display a message while setup is ongoing.

**Comment by nuxodin** [comment]
Thanks for the feedback
Since dynamically inserted styles are also taken into account afterwards, you cannot simply make a callback.
Furthermore, I no longer extend the script.
