### ISSUE TITLE
Feature Request: Process inline styles only

### ISSUE THREAD

**Issue by dotherightthing** [nuxodin/ie11CustomProperties#84]
In IE11, use of this polyfill adds a noticeable lag before the page becomes fully interactive (v4.1.0).

I've mitigated this by post-processing my CSS with postcss-custom-properties. This allows the page to render the core styles right away, with inline overrides being applied once the ie11CustomProperties polyfill has finished doing its thing.

However I assume that ie11CustomProperties is still processing the stylesheets. I'd like an option to disable processing of stylesheets, so that the ie11CustomProperties polyfill would focus on only applying the style overrides authored as inline styles. My hope is that this would decrease the run time of ie11CustomProperties.

**Comment by nuxodin** [comment]
Hi,
Sorry, i have stopped working on this Project.

**Comment by coliff** [comment]
@dotherightthing - there's a PR open (#79) which I'm hoping will be merged which may help with your issue. You'll be able to add the attribute 'iecp-ignore' to linked stylesheets so they are not processed by the polyfill.

**Comment by nuxodin** [comment]
closed with https://github.com/nuxodin/ie11CustomProperties/pull/79
