### ISSUE TITLE
Issues with nested calc()

### ISSUE THREAD

**Issue by dangelion** [nuxodin/ie11CustomProperties#86]
Hi @nuxodin, I know you discontinued the library but I hope you just could give me some idea to solve this issue.

I use `calc()` in custom properties and using variable custom properties inside other custom properties so the results are nested calc() on various levels.

I'm in this situation in which there are missing values:

**As it should be (Chrome):**
![Schermata 2021-02-04 alle 17 51 32](https://user-images.githubusercontent.com/4182418/106927274-4a62e700-6712-11eb-991d-7ffffe85a384.jpg)

**on IE11:**
![IMG_4643](https://user-images.githubusercontent.com/4182418/106927650-a88fca00-6712-11eb-8c25-ff82421eb0e8.jpg)

I'm using latest version 4.1.0

Have you any ideas what causing this problem? Hope you can find a little time to help me 🙏
Thanks

**Comment by nuxodin** [comment]
Sorry dangelion
The calc-alghorytm is too complicated.

**Comment by dangelion** [comment]
Hi @nuxodin 
you mean calc in my code or the handling of calc() by your library?

Why there are two variable definition for each one? I mean, for example:
**-ieVar--ie-**f-1-25
**-ie-**f-1-25
the first one is right while the second one has some problems.

Could you suggest a workaround (dirty is ok) to bypass my issue?
Thanks

**Comment by nuxodin** [comment]
Handling of calc by the library is complicated.

-ieVar- means a property that contains variables
-ie- means a variable

I suggest to define styles for IE11 separate, if it does not work with the polyfill.

Example:
padding:10px /* for ie11 */
padding:var(--xyz); /* for other browsers */
