### ISSUE TITLE
Does not support CSS comments?

### ISSUE THREAD

**Issue by Comawhite54** [nuxodin/ie11CustomProperties#87]
Hi, I know this great project is discontinued, but I still hope one can help with my issue:

When I add comments into my CSS, it will mess with the addon. any CSS data in the file, placed after that comment, will not be converted anymore.

code example, comment after background size cause the issue:

`.nav-button
{
    border				: none	;
    opacity				: 1	;
	background-repeat	: no-repeat	;
	background-position : 13px 50%	;
	background-size		: 35px 35px  ; /*size required for ie11 + svg*/
        background-color:  var(--thcolor_navbackground)  ;  
	border-left: 1px solid transparent;
}`

**Comment by Comawhite54** [comment]
Just found a workaround by putting a semicolomn right after the comment!!
Better than nothing!
background-size : 35px 35px ; /*size required for ie11 + svg*/ ;

**Comment by nuxodin** [comment]
As it is regex-based, its to complicated to take comments into account.
