### ISSUE TITLE
not working in angular

### ISSUE THREAD

**Issue by lenhantps** [nuxodin/ie11CustomProperties#9]
hi, i use this for my project angular 7 and this is my issue:
"-ieVar-❗background-color: var(--secondary-color);
   background-color: var(--secondary-color); 
  ".
What is ❗ ? and it does not working, please help me take a look, tks.

**Comment by nuxodin** [comment]
Hi lenhantps
❗ means its a variable containing a !important statement.
Can you send me more of the original css? Or have you a public url containing your issue?

**Comment by nuxodin** [comment]
Any news on this?

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
