### ISSUE TITLE
ShadowDOM and Web Component Support?

### ISSUE THREAD

**Issue by EisenbergEffect** [nuxodin/ie11CustomProperties#91]
Just curious if this has been tested or is supported in the context of ShadowDOM? In particular this would be a situation where ShadowDOM was polyfilled probably with ShadyDOM and ShadyCSS.

I certainly understand if this isn't supported or is untested. Just thought I'd check.

Thanks!

**Comment by nuxodin** [comment]
No, that was never taken into account.
