### ISSUE TITLE
@import'ed CSS-variables aren't affected by your script

### ISSUE THREAD

**Issue by viT-1** [nuxodin/ie11CustomProperties#92]
** Description **  
`@import`ed files with css-variables aren't working (first header should be gray).

** Version **  
4.1.0

** To Reproduce **  
[`@import` files with css-variables isn't working](https://jsbin.com/lobeyovayi/edit?html,output)

**Comment by nuxodin** [comment]
I have already noted that:
https://github.com/nuxodin/ie11CustomProperties#import
